/**
 * smart-classroom.com Inc. Copyright (c) 2015-present All Rights Reserved.
 * generated by SaberGenerator
 */
package com.smart.classroom.subscription.repository.mapper.order;

import com.smart.classroom.subscription.domain.biz.order.enums.OrderStatus;
import com.smart.classroom.subscription.repository.orm.order.OrderDO;
import com.smart.classroom.subscription.repository.orm.subscription.SubscriptionDO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface OrderMapper extends OrderBaseMapper {

    List<OrderDO> queryByReaderIdAndColumnIdAndStatuses(
            @Param("readerId") Long readerId,
            @Param("columnId") Long columnId,
            @Param("statuses") List<OrderStatus> statuses
    );

    OrderDO queryByNo(@Param("orderNo") String orderNo);

    int updateStatus(@Param("orderId") Long orderId, @Param("status") OrderStatus status);
}