/**
 * smart-classroom.com Inc. Copyright (c) 2015-present All Rights Reserved.
 * generated by SaberGenerator
 */
package com.smart.classroom.subscription.repository.mapper.order;

import com.github.pagehelper.Page;
import com.smart.classroom.subscription.domain.biz.order.enums.OrderStatus;
import com.smart.classroom.subscription.repository.mapper.base.BaseMapper;
import com.smart.classroom.subscription.repository.orm.order.OrderDO;
import com.smart.classroom.subscription.utility.enums.SortDirection;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface OrderBaseMapper extends BaseMapper<OrderDO> {

    /**
     * 当入参中含有PageNum和pageSize时，会自动分页。
     */
    Page<OrderDO> page(
            @Param("pageNum") int pageNum,
            @Param("pageSize") int pageSize,
            @Param("orderCreateTime") SortDirection orderCreateTime,
            @Param("orderUpdateTime") SortDirection orderUpdateTime,
            @Param("readerId") Long readerId,
            @Param("columnId") Long columnId,
            @Param("columnQuoteId") Long columnQuoteId,
            @Param("paymentId") Long paymentId,
            @Param("status") OrderStatus status
    );


}