/**
 * smart-classroom.com Inc. Copyright (c) 2015-present All Rights Reserved.
 * generated by SaberGenerator
 */
package com.smart.classroom.subscription.repository.mapper.subscription;

import com.smart.classroom.subscription.repository.orm.subscription.SubscriptionDO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface SubscriptionMapper extends SubscriptionBaseMapper {
    SubscriptionDO queryByReaderIdAndColumnId(@Param("readerId") Long readerId, @Param("columnId") Long columnId);
}